# Generated by Django 4.2 on 2023-05-01 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="User_Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Score", models.IntegerField()),
                (
                    "nickname",
                    models.ForeignKey(
                        db_column="nickname",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.main_user",
                    ),
                ),
            ],
            options={
                "db_table": "User_Score",
                "managed": True,
            },
        ),
    ]
