# Generated by Django 4.2 on 2023-05-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mymodel",
            name="image",
        ),
        migrations.AddField(
            model_name="mymodel",
            name="img",
            field=models.ImageField(default=0, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="mymodel",
            name="name",
            field=models.TextField(default=0, max_length=20),
        ),
        migrations.DeleteModel(
            name="User_Score",
        ),
    ]
