# Generated by Django 4.2 on 2023-05-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_remove_mymodel_image_mymodel_img_mymodel_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mymodel",
            options={"managed": False},
        ),
    ]
