# Generated by Django 4.2 on 2023-05-02 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_alter_mymodel_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="mymodel",
            table="MyModel",
        ),
    ]
